### ISSUE TITLE
Please Add Generation of ViewModel boiler plate code in Views

### ISSUE THREAD

**Issue by escamoteur** [kswoll/ReactiveUI.Fody#22]
Hi,

in all Xaml Views (Xamarin Forms e.g.) we need to add Properties so that the ViewModel can be set:

e.g.

```
    public partial class StartView : ContentPage,IViewFor<StartViewModel>
    {
        public StartView()
        {
            InitializeComponent();
        }


        public StartViewModel ViewModel
        {
            get { return (StartViewModel)GetValue(ViewModelProperty); }
            set { SetValue(ViewModelProperty, value); }
        }
        public static readonly BindableProperty ViewModelProperty =
            BindableProperty.Create<StartView, StartViewModel>(x => x.ViewModel, default(StartViewModel), BindingMode.OneWay);


        object IViewFor.ViewModel
        {
            get { return ViewModel; }
            set { ViewModel = (StartViewModel)value; }
        }

    }

```

It would be great if you could add a class attribute that would generate them automatically.

Best
Thomas

**Comment by kswoll** [comment]
Indeed that boilerplate is a nuisance.  In my own projects, I typically createa  subclass, like `RxContentPage`, that takes care of this, and then subclass that for my own views.  This works, but it's cumbersome as you have to do that for each primary view type you want to consume.

I agree it'd be great if we could decorate a class to take care of this for us.  However, the best we could probably get would be something like:

```
[ReactiveView]
public partial class StartView : ContentPage, IViewFor<StartViewModel>
{
    ...

    public StartViewModel ViewModel { get; set; }
    object IViewFor.ViewModel { get; set; }

    public static readonly BindableProperty ViewModelProperty =
        BindableProperty.Create<StartView, StartViewModel>(x => x.ViewModel, default(StartViewModel), BindingMode.OneWay);
}
```

It's important for the view to explicitly declare that it implements `IViewFor<T>` because otherwise the `this.Bind(...)` invocations will fail.  Furthermore, you'll have to still declare the `ViewModel` properties, because otherwise the class will be invalid and won't make it through the compilation phase before the Fody process has a chance to kick in.

The `BindableProperty` stuff is Xamarin.Forms-specific -- I wouldn't object to facilitating its usage, but I presume you need to be able to access `ViewModelProperty` in a static context in your code and thus relying on Fody generation would be too late.

Therefore, it seems to me that just creating your own common base classes is the best way to reduce this boilerplate in your views, and would be preferable to the end result you'd get if utilizing this proposed new attribute.

Thoughts?

**Comment by glennawatson** [comment]
I also believe that maybe a Xamarin BindableProperty Fody similar to the already existing DependencyProperty Fody one already available may be a way to reduce the boiler plate. This would be outside of scope of the Reactive fody though.
